language: node_js
node_js:
  - "14"
before_install:
  - npm install -g pnpm
install:
  - pnpm install
after_success:
  - codecov
deploy:
  provider: npm
  email: YOUR_EMAIL_ADDRESS
  api_key: YOUR_AUTH_TOKEN
  on:
    tags: true
