export const STATE_RELATES = Symbol('state-relate')
export const IDENTIFIER = Symbol('vare-identifier')
export const NAME = Symbol('name')
export const SUBSCRIPTIONS = Symbol('hooks')
export const COMPUTATION_TYPE = Symbol('computation-type')
